project/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views.advanced import OrderingView
from .views.base import GenericSearchView

urlpatterns = [
    url(r'^api/save-orderable/$', OrderingView.as_view(), name='save-orderable-view'),
    url(r'^search/$', GenericSearchView.as_view(), name='search-view'),
]

project/apps/corporate/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import MessageCreateAndSend, SubscribeToListView, GetAccessToken

from .api.views import ApiGalleryDetailView, ApiGalleryListView, ApiPhotoDetailView, ApiPhotoListView, ApiVideoEntriesList


urlpatterns = [
	url(r'^subscribe-to-list$', SubscribeToListView.as_view(), name='mailchimp-list-subscribe'),
	url(r'^send-mail$', MessageCreateAndSend.as_view(), name='send-message'),

	url(r'^get-auth-token$', GetAccessToken.as_view(), name='get_auth_token'),

	url(r'^api/galleries/(?P<pk>\d+)$', ApiGalleryDetailView.as_view(), name='api-gallery-detail'),
    url(r'^api/galleries/$', ApiGalleryListView.as_view(), name='api-galleries-list'),
    
    url(r'^api/photos/(?P<pk>\d+)$', ApiPhotoDetailView.as_view(), name='api-photo-detail'),
    url(r'^api/photos/$', ApiPhotoListView.as_view(), name='api-photos-list'),

    url(r'^api/videoentries/$', ApiVideoEntriesList.as_view(), name='api-videoentries-list'),
]

project/apps/portfolio/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import PortfolioDetailView, PortfolioItemsListView, ApiPortfolioCategoryDetailView, ApiPortfolioCategoryList, ApiPortfolioItemCategoryDetail, ApiPortfolioItemsList

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', PortfolioDetailView.as_view(), name='portfolio-detail'),
    
    url(r'^api/portfolio-items/(?P<pk>\d+)$', ApiPortfolioCategoryList.as_view(), name='api-portfolio-detail'),
    url(r'^api/portfolio-items/$', ApiPortfolioItemsList.as_view(), name='api-portfolio-list'),
    url(r'^api/portfolio-categories/$', ApiPortfolioCategoryList.as_view(), name='api-portfolio-categories-list'),
    
    url(r'^$', PortfolioItemsListView.as_view(), name='portfolio-list'),
]

project/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.views.generic import TemplateView

from filebrowser.sites import site

from rest_framework.authtoken import views

from project import settings

from django.views.static import serve


admin_patterns = [
    # Examples:
    # url(r'^$', 'reservations.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    #url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^', include('project.apps.base.urls', namespace='base')),
]

urlpatterns = [
    url(r'^api-token-auth/', views.obtain_auth_token)
]


urlpatterns += [
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,'show_indexes': True})
    ]


urlpatterns += [
    url(r'^tinymce/', include('tinymce.urls')),
]

urlpatterns += [
    url(r'^corporate/', include('project.apps.corporate.urls', namespace='corporate', app_name='corporate')), #Questa in realtà la inseriremo dagli apphook
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls')),
    ]

cms_patterns = [
    #url(r'^/?$', TemplateView.as_view(template_name="templates/home.html"), name='homepage_view'),
    url(r'^', include('cms.urls')),
]

urlpatterns += i18n_patterns(
    #url(r'^events/(?P<slug>[-\w]+)/$', EventDetailView.as_view(), name='event-detail'),
    url(r'^', include(admin_patterns, namespace='')),
    url(r'^', include(cms_patterns, namespace='')),
)

project/apps/base/views/advanced.py
# -*- coding: utf-8 -*-
""" FHCoreLibs > Views by Frankhood
    @author: Frankhood Business Solutions
"""
import operator

from django import http
from django.db import models
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpResponse, HttpResponseBadRequest
from django.utils.decorators import method_decorator
from django.utils.encoding import smart_str, force_text
from django.utils.translation import ugettext as _
from django.views.decorators.cache import never_cache
from django.views.generic.base import View

try:
    import json
except ImportError:
    from django.utils import simplejson as json

from ..exceptions import JsonException


class Autocomplete(View):
    """ Restituisce la lista degli oggetti di classe self.model il cui name inizia x term in funzione della parola mandatagli in ajax """
    model = None
    manager= 'objects'
    variable = None
    fk_variable = None
    filter_type = 'istartswith'
    slug_name = 'term'
    filter_slug_name = None
    
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(Autocomplete, self).dispatch(request, *args, **kwargs)
    
    def get_term(self):
        term = self.request.GET.get(self.slug_name)
        return term
    
    def get_filter_term(self):
        filter_term = self.request.GET.get(self.filter_slug_name, '') 
        return filter_term
    
    def get_query_set(self, term, filter_term):
        filter_args = {'%s__%s' % (self.variable, self.filter_type) :term}
        return getattr(self.model,self.manager).select_related().filter(**filter_args)
    
    def build_data(self,qs):
        data = []
        for entry in qs:
            datadict = {'label': '%s' % getattr(entry,self.variable), 'value': '%s' % getattr(entry,self.variable)}
            data.append(datadict)
        return data
    
    def get(self, request, *args, **kwargs):
        if not request.is_ajax() and not request.GET.get('term'):
            return HttpResponseBadRequest('Request not accepted')
        term = self.get_term()
        filter_term = self.get_filter_term()
        qs = self.get_query_set(term, filter_term)
        data = self.build_data(qs)
        json_data = json.dumps(data)
        return HttpResponse(json_data, mimetype='application/json')

try:
    from tagging.models import Tag

    class AutocompleteTag(Autocomplete):
    
        model = Tag
        manager= 'objects'
        variable = 'name'
        fk_variable = 'items'
        filter_type = 'icontains'
        slug_name = 'term'
        
        def build_data(self,qs):
            data = []
            for entry in qs:
                datadict = {'label': '%s(%s)' % (getattr(entry,self.variable), getattr(entry,self.fk_variable).count()), 'value': u'%s' % getattr(entry,self.variable)}
                data.append(datadict)
            return data

except ImportError as ex:
    pass

class AutocompleteForeignKey(Autocomplete):
    
    model = None
    manager= 'objects'
    slug_name = 'term'
    
    def get_model(self):
        if self.model:
            return self.model
        else:
            app_label = self.kwargs.get('app_label',None)
            model_name = self.kwargs.get('model_name',None)
            if app_label and model_name:
                model = get_model(app_label,model_name)
                if model:
                    return model
            raise ImproperlyConfigured("No model found with app_label {0} and model_name ".format(app_label,model_name))
    
    def get_query_set(self, term):
        if not self.model:
            raise ImproperlyConfigured("Model is required")
        if hasattr(self.model, self.manager):
            qs = getattr(self.model,self.manager).all()
        else:
            qs = self.model._default_manager.all()
        try:
            search = [models.Q(**{smart_str(item):smart_str(term)}) for item in self.model.autocomplete_search_fields()]
            qs = qs.filter(reduce(operator.or_, search))
        except AttributeError:
            raise JsonException('Non è possibile legare la tua entry a questo tipo di Content Type')
        return qs   
    
    def get_object(self,obj_id):
        return self.model._default_manager.filter(id=obj_id)
     
    def build_data(self,qs):
        data = []
        data = [{"value":f.pk,"label":u'%s' % force_text(f)} for f in qs[:30]]
        return data   
    
    def get_initial(self):
        initial = self.request.GET.get('initial',False)
        return initial
        
    def get(self, request, *args, **kwargs):
        if not request.is_ajax() and (not request.GET.get('term') and not request.GET.get('initial')):
            return HttpResponseBadRequest('Request not accepted')
        self.model = self.get_model()
        term = self.get_term()
        if self.get_initial():
            qs=self.get_object(term)
        else:
            try:
                qs = self.get_query_set(term)
            except JsonException as e:
                return HttpResponse(e.json_data, mimetype='application/json')
        data = self.build_data(qs)
        json_data = json.dumps(data)
        return HttpResponse(json_data, mimetype='application/json')


class AutocompleteCtype(Autocomplete):
    
    model = None
    manager= 'objects'
    slug_name = 'term'
    filter_slug_name = 'c_type'
    manager = 'not_preview_pub_objects'
    
    def get_model_by_ctype(self,c_type_id):
        try:
            ctype_obj = ContentType.objects.get(id=c_type_id)
        except ValueError:
            raise JsonException(_(u'Inserisci prima il content_type'))
        model = models.get_model(ctype_obj.app_label,ctype_obj.model)
        if not model:
            raise JsonException(_(u'Invalid Content_type'))
        return model
    
    def get_query_set(self, term, c_type_id):
        self.model = self.get_model_by_ctype(c_type_id)
        if hasattr(self.model, self.manager):
            qs = getattr(self.model,self.manager).all()
        else:
            qs = self.model._default_manager.all()
        try:
            search = [models.Q(**{smart_str(item):smart_str(term)}) for item in self.model.autocomplete_search_fields()]
            qs = qs.filter(reduce(operator.or_, search))
        except AttributeError:
            raise JsonException('Non è possibile legare la tua entry a questo tipo di Content Type')
        return qs   
    
    def get_object(self,obj_id, c_type_id):
        self.model = self.get_model_by_ctype(c_type_id)
        return self.model._default_manager.filter(id=obj_id)
     
    def build_data(self,qs):
        data = []
        data = [{"value":f.pk,"label":u'%s' % force_text(f)} for f in qs[:10]]
        return data   
    
    def get_initial(self):
        initial = self.request.GET.get('initial',False)
        return initial
        
    def get(self, request, *args, **kwargs):
        if not request.is_ajax() and (not request.GET.get('term') and not request.GET.get('initial')):
            return HttpResponseBadRequest('Request not accepted')
        term = self.get_term()
        filter_term = self.get_filter_term()
        if self.get_initial():
            qs=self.get_object(term, filter_term)
        else:
            try:
                qs = self.get_query_set(term, filter_term)
            except JsonException as e:
                return HttpResponse(e.json_data, mimetype='application/json')
        data = self.build_data(qs)
        json_data = json.dumps(data)
        return HttpResponse(json_data, mimetype='application/json')
    
class OrderingView(View):
 
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(OrderingView, self).dispatch(request, *args, **kwargs)  

   
    def save_item(self,**kwargs):
        _c_type = ContentType.objects.get(app_label=kwargs['app_label'][5:], model=kwargs['app_model'])
        _object = _c_type.get_object_for_this_type(id=kwargs['obj_id'])
        setattr(_object, kwargs['order_field'], kwargs['new_order'])
        _object.save()
        return _c_type.model_class().objects.values('id', kwargs['order_field'])

    
    def get(self, request, *args, **kwargs):
        data= None
        if all([self.request.GET.has_key('order_field'),
                self.request.GET.has_key('app_label'),
                self.request.GET.has_key('app_model'),
                self.request.GET.has_key('obj_id'),
                self.request.GET.has_key('new_order')]):
            data = self.save_item(**(dict(order_field= self.request.GET.get('order_field'),
                                   app_label= self.request.GET.get('app_label'),
                                   app_model= self.request.GET.get('app_model'),
                                   obj_id=long(self.request.GET.get('obj_id')),
                                   new_order=long(self.request.GET.get('new_order'))
                                   )))
        json_data = json.dumps(list(data)) 
        return HttpResponse(json_data)       

project/apps/base/views/base.py
# -*- coding: utf-8 -*-
from django.db.models import Q
from django.http import Http404
from django.utils.translation import ugettext as _
from django.views.generic.base import TemplateView

from project.apps.corporate.models import News, Event, PressRelease

class GenericSearchView(TemplateView):

    template_name = "corporate/search_results.html"

    def dispatch(self, request, *args, **kwargs):
        # Try to dispatch to the right method; if a method doesn't exist,
        # defer to the error handler. Also defer to the error handler if the
        # request method isn't on the approved list.
        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed
        return handler(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.search =  request.POST.get("search", None)
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(GenericSearchView, self).get_context_data(**kwargs)
        
        context["search"] = self.search

        news = News.published_objects.filter(
            Q(title__icontains=self.search) | Q(content__icontains=self.search)
        )
        pressrelease = PressRelease.published_objects.filter(
            Q(title__icontains=self.search) | Q(content__icontains=self.search)
        )
        events = Event.published_objects.filter(
            Q(title__icontains=self.search) | Q(content__icontains=self.search)
        )

        context["news"] = news
        context["events"] = events
        context["pressrelease"] = pressrelease

        context["count"] = news.count() + events.count() + pressrelease.count()

        return context

project/apps/corporate/api/views.py
# -*- coding: utf-8 -*-

from photologue.models import Gallery, Photo
from rest_framework import generics

from ..models import Event, EventCategory, News, NewsCategory, VideoEntry, PressRelease
from ..serializers.events import EventSerializer, EventCategorySerializer
from ..serializers.gallery import GallerySerializer, PhotoSerializer
from ..serializers.news import NewsSerializer, NewsCategorySerializer
from ..serializers.pressrelease import PressReleaseSerializer
from ..serializers.videoentries import VideoEntrySerializer


# event api 
class ApiEventDetailView(generics.RetrieveAPIView):
	queryset = Event.published_objects.all()
	serializer_class = EventSerializer

class ApiEventsList(generics.ListAPIView):
    queryset = Event.published_objects.all()
    serializer_class = EventSerializer


class ApiEventCategoryDetail(generics.RetrieveAPIView):
	queryset = EventCategory.published_objects.all()
	serializer_class = EventCategorySerializer

class ApiEventCategoriesList(generics.ListAPIView):
	queryset = EventCategory.published_objects.all()
	serializer_class = EventCategorySerializer



# gallery api views (urls in project.apps.corporate.urls)
class ApiGalleryDetailView(generics.RetrieveAPIView):
	queryset = Gallery.objects.all()
	serializer_class = GallerySerializer

class ApiGalleryListView(generics.ListAPIView):
	queryset = Gallery.objects.all()
	serializer_class = GallerySerializer

class ApiPhotoDetailView(generics.RetrieveAPIView):
	queryset = Photo.objects.all()
	serializer_class = PhotoSerializer

class ApiPhotoListView(generics.ListAPIView):
	queryset = Photo.objects.all()
	serializer_class = PhotoSerializer


#news api views
class ApiNewsDetailView(generics.RetrieveAPIView):
	queryset = News.published_objects.all()
	serializer_class = NewsSerializer

class ApiNewsList(generics.ListAPIView):
    queryset = News.published_objects.all()
    serializer_class = NewsSerializer


class ApiNewsCategoryDetail(generics.RetrieveAPIView):
	queryset = NewsCategory.published_objects.all()
	serializer_class = NewsCategorySerializer

class ApiNewsCategoriesList(generics.ListAPIView):
	queryset = NewsCategory.published_objects.all()
	serializer_class = NewsCategorySerializer

#video entries views (urls in project.apps.corporate.urls)
class ApiVideoEntriesList(generics.ListAPIView):
	queryset = VideoEntry.published_objects.all()
	serializer_class = VideoEntrySerializer


#press release views
class ApiPressReleaseDetail(generics.RetrieveAPIView):
	queryset = PressRelease.published_objects.all()
	serializer_class = PressReleaseSerializer

class ApiPressReleaseList(generics.ListAPIView):
	queryset = PressRelease.published_objects.all()
	serializer_class = PressReleaseSerializer

project/templates/corporate/event_detail.html
{% extends 'base_site.html' %}
{% load thumbnail %}
{% load cms_tags %}
{% load i18n %}
{% load static from staticfiles %}

{% block og_sharing_meta %}

<meta property="og:url"                content="{{ request.build_absolute_uri }}" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="{{object.title}}" />
<meta property="og:description"        content="{% spaceless %}{{object.excerpt|striptags}}{% endspaceless %}" />
{% thumbnail object.cover_img.image "1920x1080" crop="center" as im %}
<meta property="og:image"              content="http://{{request.get_host}}{{im.url}}" />
{% endthumbnail %}

{% endblock og_sharing_meta %}

{% block extra_header %}
	<!-- Project Top -->
	<div class="project-img" id="project-img">
		{% thumbnail object.cover_img.image "1860x680" crop="center" as im %}
			<img src="{{im.url}}" alt="{{object.title}}" class="hideMobile">
			<div class="hideTablet hideDesktop bgImage" style="background-image:url({{im.url}})" ></div>
		{% endthumbnail %}
		<span class="line-ct"></span>
		{% if prev %}<a class="project-prev" href="{% url 'portfolio:portfolio-detail' slug=prev.slug %}">Prev project</a>{% endif %}
		{% if next_item %}<a class="project-next" href="{% url 'portfolio:portfolio-detail' slug=next_item.slug %}">Next project</a>{% endif %}
	</div>
	<!-- /Project Top-->
{% endblock extra_header %}

{% block page_content %}
	<div class="cont">
		<div class="post">
			<!-- Post Content -->
			<div class="post-info">
				<time datetime="{{object.event_start_date|date:"Y-m-d H:i"}}">
					<span>{{object.event_start_date|date:"d"}}</span>
					{{object.event_start_date|date:"F"}}
				</time>
				{% for c in object.categories.all %}
					<a href="#">{{c.name}}</a>{% if not forloop.last %},{% endif %}
				{% empty %}
				{% endfor %}
				<h1>Nam consequat est at arcu scelerisque, nec malesuada diam eleifend</h1>
			</div>
			{% if object.gallery %}
			<!-- Project - Carousel -->
			<div class="post-slider">
				<ul class="slides">
				{% for photo in object.gallery.photos.all %}
					{% thumbnail photo.image "1102x571" crop="center" as im %}
					<li>
						<img src="{{im.url}}" alt="{{im.name}}">
					</li>
					{% endthumbnail %}
				{% empty %}
				{% endfor %}
				
			</div>
			<!-- / Project - Carousel -->
			{% endif %}
			<article class="postContent">
				{{object.content|safe}}
			</article>
			<!-- Post Content -->

			<!-- Social Share -->
			<ul class="post-share">
				<li><a data-social="facebook" href="#" title="Share on Facebook" class="js-fbShare"><i class="fa fa-facebook"></i></a></li>
				<li><a data-social="twitter" href="#" title="Tweet" class="js-twitterShare"><i class="fa fa-twitter"></i></a></li>
				{% comment %}
				<li><a data-social="mail" href="#" target="_blank" title="Pin it" class="mailShare"><i class="fa fa-envelope"></i></a></li>
				{% endcomment %}
			</ul>
			<!-- Social Share -->

		</div>
	</div>
	<p class="post-showmore">
		<a data-goto="#page" href="#">Back to top</a>
	</p>
{% endblock page_content %}

project/templates/corporate/events_categories_list.html
{% extends 'base_site.html' %}
{% load cms_tags %}
{% load menu_tags %}
{% load thumbnail %}
{% load i18n %}

{# show_menu 0 100 100 100 #}
{% block page_content %}
    
    <div id="content" class="site-content">

        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                {% thumbnail object.cover_img.image "1920x950" crop="center" as im %}
                <div class="page-styling page-topttl page-topttl-light" style="background: url({{im.url}});margin-top: -30px;margin-bottom: 50px;">
                {% endthumbnail %}
                    <ul class="b-crumbs">
                        <li>
                            <a class="first-item" href="/">Home</a>
                        </li>
                        <li>
                            <span class="last-item">{{object.name}}</span>
                        </li>
                    </ul>
                    <h2 style="color:#fff">{{object.name}}</h2>
                    {% if object.abstract %}{{object.abstract|safe}}{% else %}{{object.content|safe}}{% endif %}
                </div>
                <h3 class="tac" style="margin-bottom:30px;">Prossimi appuntamenti</h3>
                <div class="cont cont-widthsm project-list-wrap">
                    <div class="cont project-front-sections-wrap" id="project-front-sections">
                        <div class="project-front-sections-inner">
                            <ul class="project-front-sections js-filtersWrapper">
                            </ul>
                        </div>
                    </div>
                    <div class="project-front-list js-entriesWrapper" id="project-front-list">
                        {% for item in object_list %}
                        <!-- item -->
                        <div class="project-front project-front-width2 other travels">
                            <a href="http://verve.real-web.pro/verve_projects/curabitur-sed-sapien/" class="project-front-link">
                                <img width="600" height="305" src="http://verve.real-web.pro/wp-content/uploads/2016/06/fox-1477172_1920-600x305.jpg" class="attachment-verve_projects_2 size-verve_projects_2 wp-post-image" alt="">
                                <div class="project-front-cont">
                                    <p class="project-front-sect">
                                        Other,&nbsp;Travels
                                    </p>
                                    <h3>Curabitur sed sapien</h3>
                                </div>
                            </a>
                        </div>
                        <!-- /item -->
                        {% empty %}
                        {% endfor %}                        
                    </div>
                    {% comment %}
                    <ul class="page-numbers">
                        <li><span class="page-numbers current">1</span></li>
                        <li><a class="page-numbers" href="http://verve.real-web.pro/projects/page/2/">2</a></li>
                        <li><a class="next page-numbers" href="http://verve.real-web.pro/projects/page/2/">Next <i class="fa fa-angle-right"></i></a></li>
                    </ul>
                    {% endcomment %}
                </div>

            </main>
            <!-- #main -->
        </div>
        <!-- #primary -->
    </div>
</div>
{% endblock page_content %}

{% block inline_js %}
    <script type="text/javascript">
        Project.Vars.detailTemplateId = '#eventTemplateId';
        Project.Objects.currentPageView = new Views.ListView({
            listViewUrl: '{% url "events:api-events-list" %}',
            autoLoad: true
        });
    </script>
{% endblock inline_js %}

project/templates/corporate/events_list.html
{% extends 'base_site.html' %}
{% load cms_tags %}
{% load menu_tags %}
{% load thumbnail %}
{% load i18n %}

{# show_menu 0 100 100 100 #}
{% block page_content %}
    Events list
    <div class="js-entriesWrapper">
    {% for item in object_list %}
        <div>
            <a class="readMore" href="{% url 'events:event-detail' slug=item.slug %}">
                {{item.title}}
            </a>
        </div>
    {% empty %}
        Empty
    {% endfor %}
    </div>
{% endblock page_content %}

{% block inline_js %}
    <script type="text/javascript">
        Project.Vars.detailTemplateId = '#detailTemplateId';
        Project.Objects.currentPageView = new Views.ListView({
            listViewUrl: '{% url "events:api-events-list" %}',
            autoLoad: true
        });
    </script>
{% endblock inline_js %}

project/templates/corporate/gallery_list.html
{% extends 'base_site.html' %}
{% load cms_tags %}
{% load menu_tags %}
{% load thumbnail %}
{% load i18n %}

{# show_menu 0 100 100 100 #}
{% block page_content %}
    Galleries list
    <div class="js-entriesWrapper">
    {% for item in object_list %}
        <div>
            <a class="readMore" href="{% url 'gallery:gallery-detail' pk=item.id %}">
                {{item.title}}
            </a>
        </div>
    {% empty %}
    </div>
    {% endfor %}
{% endblock page_content %}

{% block inline_js %}
    <script type="text/javascript">
        Project.Vars.detailTemplateId = '#detailTemplateId';
        Project.Objects.currentPageView = new Views.ListView({
            listViewUrl: '{% url "corporate:api-galleries-list" %}',
            autoLoad: true
        });
    </script>
{% endblock inline_js %}

project/templates/corporate/news_detail.html
{% extends 'base_site.html' %}
{% load thumbnail %}
{% load i18n %}

{% block og_sharing_meta %}

<meta property="og:url"                content="{{ request.build_absolute_uri }}" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="{{object.title}}" />
<meta property="og:description"        content="{% spaceless %}{{object.excerpt|striptags}}{% endspaceless %}" />
{% thumbnail object.cover_img.image "1920x1080" crop="center" as im %}
<meta property="og:image"              content="http://{{request.get_host}}{{im.url}}" />
{% endthumbnail %}

{% endblock og_sharing_meta %}

{% block page_content %}
	{{ object.title }}
{% endblock page_content %}

project/templates/corporate/videos.html
{% extends 'base_site.html' %}
{% load cms_tags %}
{% load menu_tags %}
{% load thumbnail %}
{% load i18n %}
{% load static from staticfiles %}

{% block body_attrs %}class="videoNs"{% endblock body_attrs %}

{% block page_css %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{% static 'js/bower_components/video.js/dist/video-js.min.css' %}" />
{% endblock page_css %}
	
{% block page_content %}
		<main>
            	<h2 class="title tac">VIDEO</h2>
				<video
				    id="player"
				    class="video-js vjs-default-skin"
				    width="640" height="264"
				    >
				</video>
	            <div class="container">
					<div class="row js-entriesWrapper">
						{% for instance in object_list %}
					        <div class="videoEntry">
					            {% if instance.cover_img %}
					            <div class="imgWrapper">
									{% thumbnail instance.cover_img "400x300" crop="center" as im %}
										<a href="#" class="js-playVideo">
					                        <img src="{{ im.url }}" alt="{{ instance.title }}" />
					                    </a>
					            	{% endthumbnail %}
					            </div>
					            {% else %}
					            <div class="thumbWrapper">
					                <a href="#" class="js-playVideo">
					                </a>
					            </div>
					            {% endif %}
					            <h4>{{instance.title}}</h4>
					            {% if instance.subtitle %}<h5>{{instance.subtitle}}</h5>{% endif %}
					            <p>{{instance.content|safe}}</p>
							</div>
                        {% empty %}
                        {% endfor %}
					</div>
	            </div>
		</main>
{% endblock page_content %}

{% block inline_js %}
    <script type="text/javascript">
        Project.Vars.detailTemplateId = '#videoTemplateId';
        Project.Objects.currentPageView = new Views.VideoListView({
            listViewUrl: '{% url "corporate:api-videoentries-list" %}',
            detailViewClass: Project.Views.VideoDetailView,
            autoLoad: true
        });
    </script>
{% endblock inline_js %}