project/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views.advanced import OrderingView
from .views.base import GenericSearchView

urlpatterns = [
    url(r'^api/save-orderable/$', OrderingView.as_view(), name='save-orderable-view'),
    url(r'^search/$', GenericSearchView.as_view(), name='search-view'),
]

project/apps/corporate/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import MessageCreateAndSend, SubscribeToListView, GetAccessToken

from .api.views import ApiGalleryDetailView, ApiGalleryListView, ApiPhotoDetailView, ApiPhotoListView, ApiVideoEntriesList


urlpatterns = [
	url(r'^subscribe-to-list$', SubscribeToListView.as_view(), name='mailchimp-list-subscribe'),
	url(r'^send-mail$', MessageCreateAndSend.as_view(), name='send-message'),

	url(r'^get-auth-token$', GetAccessToken.as_view(), name='get_auth_token'),

	url(r'^api/galleries/(?P<pk>\d+)$', ApiGalleryDetailView.as_view(), name='api-gallery-detail'),
    url(r'^api/galleries/$', ApiGalleryListView.as_view(), name='api-galleries-list'),
    
    url(r'^api/photos/(?P<pk>\d+)$', ApiPhotoDetailView.as_view(), name='api-photo-detail'),
    url(r'^api/photos/$', ApiPhotoListView.as_view(), name='api-photos-list'),

    url(r'^api/videoentries/$', ApiVideoEntriesList.as_view(), name='api-videoentries-list'),
]

project/apps/portfolio/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import PortfolioDetailView, PortfolioItemsListView, ApiPortfolioCategoryDetailView, ApiPortfolioCategoryList, ApiPortfolioItemCategoryDetail, ApiPortfolioItemsList

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', PortfolioDetailView.as_view(), name='portfolio-detail'),
    
    url(r'^api/portfolio-items/(?P<pk>\d+)$', ApiPortfolioCategoryList.as_view(), name='api-portfolio-detail'),
    url(r'^api/portfolio-items/$', ApiPortfolioItemsList.as_view(), name='api-portfolio-list'),
    url(r'^api/portfolio-categories/$', ApiPortfolioCategoryList.as_view(), name='api-portfolio-categories-list'),
    
    url(r'^$', PortfolioItemsListView.as_view(), name='portfolio-list'),
]

project/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.views.generic import TemplateView

from filebrowser.sites import site

from rest_framework.authtoken import views

from project import settings

from django.views.static import serve


admin_patterns = [
    # Examples:
    # url(r'^$', 'reservations.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    #url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^', include('project.apps.base.urls', namespace='base')),
]

urlpatterns = [
    url(r'^api-token-auth/', views.obtain_auth_token)
]


urlpatterns += [
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,'show_indexes': True})
    ]


urlpatterns += [
    url(r'^tinymce/', include('tinymce.urls')),
]

urlpatterns += [
    url(r'^corporate/', include('project.apps.corporate.urls', namespace='corporate', app_name='corporate')), #Questa in realtà la inseriremo dagli apphook
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls')),
    ]

cms_patterns = [
    #url(r'^/?$', TemplateView.as_view(template_name="templates/home.html"), name='homepage_view'),
    url(r'^', include('cms.urls')),
]

urlpatterns += i18n_patterns(
    #url(r'^events/(?P<slug>[-\w]+)/$', EventDetailView.as_view(), name='event-detail'),
    url(r'^', include(admin_patterns, namespace='')),
    url(r'^', include(cms_patterns, namespace='')),
)

project/apps/base/views/advanced.py
# -*- coding: utf-8 -*-
""" FHCoreLibs > Views by Frankhood
    @author: Frankhood Business Solutions
"""
import operator

from django import http
from django.db import models
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpResponse, HttpResponseBadRequest
from django.utils.decorators import method_decorator
from django.utils.encoding import smart_str, force_text
from django.utils.translation import ugettext as _
from django.views.decorators.cache import never_cache
from django.views.generic.base import View

try:
    import json
except ImportError:
    from django.utils import simplejson as json

from ..exceptions import JsonException


class Autocomplete(View):
    """ Restituisce la lista degli oggetti di classe self.model il cui name inizia x term in funzione della parola mandatagli in ajax """
    model = None
    manager= 'objects'
    variable = None
    fk_variable = None
    filter_type = 'istartswith'
    slug_name = 'term'
    filter_slug_name = None
    
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(Autocomplete, self).dispatch(request, *args, **kwargs)
    
    def get_term(self):
        term = self.request.GET.get(self.slug_name)
        return term
    
    def get_filter_term(self):
        filter_term = self.request.GET.get(self.filter_slug_name, '') 
        return filter_term
    
    def get_query_set(self, term, filter_term):
        filter_args = {'%s__%s' % (self.variable, self.filter_type) :term}
        return getattr(self.model,self.manager).select_related().filter(**filter_args)
    
    def build_data(self,qs):
        data = []
        for entry in qs:
            datadict = {'label': '%s' % getattr(entry,self.variable), 'value': '%s' % getattr(entry,self.variable)}
            data.append(datadict)
        return data
    
    def get(self, request, *args, **kwargs):
        if not request.is_ajax() and not request.GET.get('term'):
            return HttpResponseBadRequest('Request not accepted')
        term = self.get_term()
        filter_term = self.get_filter_term()
        qs = self.get_query_set(term, filter_term)
        data = self.build_data(qs)
        json_data = json.dumps(data)
        return HttpResponse(json_data, mimetype='application/json')

try:
    from tagging.models import Tag

    class AutocompleteTag(Autocomplete):
    
        model = Tag
        manager= 'objects'
        variable = 'name'
        fk_variable = 'items'
        filter_type = 'icontains'
        slug_name = 'term'
        
        def build_data(self,qs):
            data = []
            for entry in qs:
                datadict = {'label': '%s(%s)' % (getattr(entry,self.variable), getattr(entry,self.fk_variable).count()), 'value': u'%s' % getattr(entry,self.variable)}
                data.append(datadict)
            return data

except ImportError as ex:
    pass

class AutocompleteForeignKey(Autocomplete):
    
    model = None
    manager= 'objects'
    slug_name = 'term'
    
    def get_model(self):
        if self.model:
            return self.model
        else:
            app_label = self.kwargs.get('app_label',None)
            model_name = self.kwargs.get('model_name',None)
            if app_label and model_name:
                model = get_model(app_label,model_name)
                if model:
                    return model
            raise ImproperlyConfigured("No model found with app_label {0} and model_name ".format(app_label,model_name))
    
    def get_query_set(self, term):
        if not self.model:
            raise ImproperlyConfigured("Model is required")
        if hasattr(self.model, self.manager):
            qs = getattr(self.model,self.manager).all()
        else:
            qs = self.model._default_manager.all()
        try:
            search = [models.Q(**{smart_str(item):smart_str(term)}) for item in self.model.autocomplete_search_fields()]
            qs = qs.filter(reduce(operator.or_, search))
        except AttributeError:
            raise JsonException('Non è possibile legare la tua entry a questo tipo di Content Type')
        return qs   
    
    def get_object(self,obj_id):
        return self.model._default_manager.filter(id=obj_id)
     
    def build_data(self,qs):
        data = []
        data = [{"value":f.pk,"label":u'%s' % force_text(f)} for f in qs[:30]]
        return data   
    
    def get_initial(self):
        initial = self.request.GET.get('initial',False)
        return initial
        
    def get(self, request, *args, **kwargs):
        if not request.is_ajax() and (not request.GET.get('term') and not request.GET.get('initial')):
            return HttpResponseBadRequest('Request not accepted')
        self.model = self.get_model()
        term = self.get_term()
        if self.get_initial():
            qs=self.get_object(term)
        else:
            try:
                qs = self.get_query_set(term)
            except JsonException as e:
                return HttpResponse(e.json_data, mimetype='application/json')
        data = self.build_data(qs)
        json_data = json.dumps(data)
        return HttpResponse(json_data, mimetype='application/json')


class AutocompleteCtype(Autocomplete):
    
    model = None
    manager= 'objects'
    slug_name = 'term'
    filter_slug_name = 'c_type'
    manager = 'not_preview_pub_objects'
    
    def get_model_by_ctype(self,c_type_id):
        try:
            ctype_obj = ContentType.objects.get(id=c_type_id)
        except ValueError:
            raise JsonException(_(u'Inserisci prima il content_type'))
        model = models.get_model(ctype_obj.app_label,ctype_obj.model)
        if not model:
            raise JsonException(_(u'Invalid Content_type'))
        return model
    
    def get_query_set(self, term, c_type_id):
        self.model = self.get_model_by_ctype(c_type_id)
        if hasattr(self.model, self.manager):
            qs = getattr(self.model,self.manager).all()
        else:
            qs = self.model._default_manager.all()
        try:
            search = [models.Q(**{smart_str(item):smart_str(term)}) for item in self.model.autocomplete_search_fields()]
            qs = qs.filter(reduce(operator.or_, search))
        except AttributeError:
            raise JsonException('Non è possibile legare la tua entry a questo tipo di Content Type')
        return qs   
    
    def get_object(self,obj_id, c_type_id):
        self.model = self.get_model_by_ctype(c_type_id)
        return self.model._default_manager.filter(id=obj_id)
     
    def build_data(self,qs):
        data = []
        data = [{"value":f.pk,"label":u'%s' % force_text(f)} for f in qs[:10]]
        return data   
    
    def get_initial(self):
        initial = self.request.GET.get('initial',False)
        return initial
        
    def get(self, request, *args, **kwargs):
        if not request.is_ajax() and (not request.GET.get('term') and not request.GET.get('initial')):
            return HttpResponseBadRequest('Request not accepted')
        term = self.get_term()
        filter_term = self.get_filter_term()
        if self.get_initial():
            qs=self.get_object(term, filter_term)
        else:
            try:
                qs = self.get_query_set(term, filter_term)
            except JsonException as e:
                return HttpResponse(e.json_data, mimetype='application/json')
        data = self.build_data(qs)
        json_data = json.dumps(data)
        return HttpResponse(json_data, mimetype='application/json')
    
class OrderingView(View):
 
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(OrderingView, self).dispatch(request, *args, **kwargs)  

   
    def save_item(self,**kwargs):
        _c_type = ContentType.objects.get(app_label=kwargs['app_label'][5:], model=kwargs['app_model'])
        _object = _c_type.get_object_for_this_type(id=kwargs['obj_id'])
        setattr(_object, kwargs['order_field'], kwargs['new_order'])
        _object.save()
        return _c_type.model_class().objects.values('id', kwargs['order_field'])

    
    def get(self, request, *args, **kwargs):
        data= None
        if all([self.request.GET.has_key('order_field'),
                self.request.GET.has_key('app_label'),
                self.request.GET.has_key('app_model'),
                self.request.GET.has_key('obj_id'),
                self.request.GET.has_key('new_order')]):
            data = self.save_item(**(dict(order_field= self.request.GET.get('order_field'),
                                   app_label= self.request.GET.get('app_label'),
                                   app_model= self.request.GET.get('app_model'),
                                   obj_id=long(self.request.GET.get('obj_id')),
                                   new_order=long(self.request.GET.get('new_order'))
                                   )))
        json_data = json.dumps(list(data)) 
        return HttpResponse(json_data)       

project/apps/base/views/base.py
# -*- coding: utf-8 -*-
from django.db.models import Q
from django.http import Http404
from django.utils.translation import ugettext as _
from django.views.generic.base import TemplateView

from project.apps.corporate.models import News, Event, PressRelease

class GenericSearchView(TemplateView):

    template_name = "corporate/search_results.html"

    def dispatch(self, request, *args, **kwargs):
        # Try to dispatch to the right method; if a method doesn't exist,
        # defer to the error handler. Also defer to the error handler if the
        # request method isn't on the approved list.
        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed
        return handler(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.search =  request.POST.get("search", None)
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(GenericSearchView, self).get_context_data(**kwargs)
        
        context["search"] = self.search

        news = News.published_objects.filter(
            Q(title__icontains=self.search) | Q(content__icontains=self.search)
        )
        pressrelease = PressRelease.published_objects.filter(
            Q(title__icontains=self.search) | Q(content__icontains=self.search)
        )
        events = Event.published_objects.filter(
            Q(title__icontains=self.search) | Q(content__icontains=self.search)
        )

        context["news"] = news
        context["events"] = events
        context["pressrelease"] = pressrelease

        context["count"] = news.count() + events.count() + pressrelease.count()

        return context

project/apps/corporate/api/views.py
# -*- coding: utf-8 -*-

from photologue.models import Gallery, Photo
from rest_framework import generics

from ..models import Event, EventCategory, News, NewsCategory, VideoEntry, PressRelease
from ..serializers.events import EventSerializer, EventCategorySerializer
from ..serializers.gallery import GallerySerializer, PhotoSerializer
from ..serializers.news import NewsSerializer, NewsCategorySerializer
from ..serializers.pressrelease import PressReleaseSerializer
from ..serializers.videoentries import VideoEntrySerializer


# event api 
class ApiEventDetailView(generics.RetrieveAPIView):
	queryset = Event.published_objects.all()
	serializer_class = EventSerializer

class ApiEventsList(generics.ListAPIView):
    queryset = Event.published_objects.all()
    serializer_class = EventSerializer


class ApiEventCategoryDetail(generics.RetrieveAPIView):
	queryset = EventCategory.published_objects.all()
	serializer_class = EventCategorySerializer

class ApiEventCategoriesList(generics.ListAPIView):
	queryset = EventCategory.published_objects.all()
	serializer_class = EventCategorySerializer



# gallery api views (urls in project.apps.corporate.urls)
class ApiGalleryDetailView(generics.RetrieveAPIView):
	queryset = Gallery.objects.all()
	serializer_class = GallerySerializer

class ApiGalleryListView(generics.ListAPIView):
	queryset = Gallery.objects.all()
	serializer_class = GallerySerializer

class ApiPhotoDetailView(generics.RetrieveAPIView):
	queryset = Photo.objects.all()
	serializer_class = PhotoSerializer

class ApiPhotoListView(generics.ListAPIView):
	queryset = Photo.objects.all()
	serializer_class = PhotoSerializer


#news api views
class ApiNewsDetailView(generics.RetrieveAPIView):
	queryset = News.published_objects.all()
	serializer_class = NewsSerializer

class ApiNewsList(generics.ListAPIView):
    queryset = News.published_objects.all()
    serializer_class = NewsSerializer


class ApiNewsCategoryDetail(generics.RetrieveAPIView):
	queryset = NewsCategory.published_objects.all()
	serializer_class = NewsCategorySerializer

class ApiNewsCategoriesList(generics.ListAPIView):
	queryset = NewsCategory.published_objects.all()
	serializer_class = NewsCategorySerializer

#video entries views (urls in project.apps.corporate.urls)
class ApiVideoEntriesList(generics.ListAPIView):
	queryset = VideoEntry.published_objects.all()
	serializer_class = VideoEntrySerializer


#press release views
class ApiPressReleaseDetail(generics.RetrieveAPIView):
	queryset = PressRelease.published_objects.all()
	serializer_class = PressReleaseSerializer

class ApiPressReleaseList(generics.ListAPIView):
	queryset = PressRelease.published_objects.all()
	serializer_class = PressReleaseSerializer

project/templates/cms_templates/about_us.html
{% extends 'base_site.html' %} {% load cms_tags %} {% load menu_tags %} {% load events_tags %} {% load i18n %} {% load static from staticfiles %}

{% block body_attrs %}class="aboutUsNs"{% endblock body_attrs %} 

{% block header %}
    <div id="page" class="page">
    <!-- Header -->
        <header class="header site-header">
            <!-- Logotype -->
            <div class="mainmenu-btn" id="mainmenu-btn">
                <div class="navTrigger"><i></i></div>
            </div>
            <!-- Search Form -->
            <div class="header-search searchFormWrapper">
                <a href="#" id="header-search-btn" class="header-search-btn"><i class="fa fa-search"></i></a>
                <form id="header-search" class='' method="post" action="{% url 'base:search-view' %}">
                    {% csrf_token %}
                    <fieldset>
                        <div class="contact-form_block1 btn-wr">
                            <label class="query">
                                <input type="text" name="search" placeholder="{% trans 'Search into website' %}:" value="" data-constraints="@Required" />
                            </label>
                            <button type="submit" class="header-search-btn submit-btn" id="header-search-btn" value="{% trans 'Search' %}">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </header>
    <!-- Header -->
    {% block extra_header %}
    {% placeholder 'Top container' %}
    <span class="line-ct-wrap"><span class="line-ct"></span></span>
    {% endblock extra_header %}
</div>
{% endblock header %}

{% block page_content %}
<main id="main" class="site-main">
    <div class="cont">
        <div class="post project vc_row vc_row-fluid row-width-container">
            <div class="vc_column_container vc_col-sm-12">
                <div class="vc_column-inner ">
                    <div class="">
                        <h2 style="font-size: 30px;text-align: center" class="vc_custom_heading vc_custom_1467564414051">ABOUT FACTOR HILL</h2>
                        <div class="wpb_text_column wpb_content_element ">
                            <div class="">
                                {% placeholder 'Bio' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="vc_row vc_row-fluid row-width-container staff ">
            <div class="vc_column_container vc_col-sm-12">
                <div class="vc_column-inner ">
                    <div class="staffWrapper">
                    	{% placeholder 'Staff' %}
                        {% comment %}
                        <div class="team-wrap team-col_3">
                        </div>
                        {% endcomment %}
                    </div>
                    <div class="staffDetailWrapper">
                        <div class="detail"></div>
                        <div class="close">
                            <a href="#" class="js-closeStaffDetail">X</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock page_content %}

project/templates/cms_templates/contacts.html
{% extends 'base_site.html' %}
{% load cms_tags %}
{% load menu_tags %}
{% load events_tags %}
{% load i18n %}

{% block body_attrs %}class="contactsNs"{% endblock body_attrs %}
{% block extra_header %}
<!-- Contacts -->
<div class="page-cont-wrap">
	<div class="cont page-cont contacts">
		<div class="contacts-form">
			<h2 class="contactsTitle">Contact Us</h2>
			<!-- Contact Form -->
			<form id="contactForm" method="post" class="form" role="form" data-url="{% url 'corporate:send-message' %}"> 
				{% csrf_token %}
				<input data-required="text" type="text" placeholder="Name" name="name" class="js-required js-validation">
				<input data-required="text" data-required-email="email" type="text" placeholder="Email address" name="sender_email" class="js-required js-emailValidation js-validation">
				<textarea data-required="text" placeholder="Subject" name="subject" class="js-required js-validation"></textarea>
				<textarea data-required="text" placeholder="Message" name="body" class="js-required js-validation"></textarea>
				<button type="submit" class="cf_send_message">Send <i class="fa fa-angle-right"></i></button>
			</form>
		</div>
		{% placeholder 'Contacts and address' %}
		<!-- Map -->
		<div class="contacts-map" id="contacts-map"></div>
	</div>
</div>
<span class="line-ct-wrap"><span class="line-ct"></span></span>
<!-- Contacts -->
{% endblock extra_header %}

{% block inline_js %}
	<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYBYfj2RnA2OBzcAmHjxxCx-kYhA_jY_E&callback=initMap">
    </script>
    <script type="text/javascript">
    	function initMap(){
    		Project.Objects.currentPageView = new Views.ContactsPageView();
    	}
    </script>
{% endblock inline_js %}

project/templates/cms_templates/generic.html
{% extends 'base_site.html' %}
{% load cms_tags %}
{% load menu_tags %}
{% load events_tags %}
{% load i18n %}
{% load static from staticfiles %}

{% block body_attrs %}class="genericNs"{% endblock body_attrs %}
{% block header %}
    <div id="page" class="page">
    <!-- Header -->
        <header class="header site-header">
            <!-- Logotype -->
            <div class="mainmenu-btn" id="mainmenu-btn">
                <div class="navTrigger"><i></i></div>
            </div>
            <!-- Search Form -->
            <div class="header-search searchFormWrapper">
                <a href="#" id="header-search-btn" class="header-search-btn"><i class="fa fa-search"></i></a>
                <form id="header-search" class='' method="post" action="{% url 'base:search-view' %}">
                    {% csrf_token %}
                    <fieldset>
                        <div class="contact-form_block1 btn-wr">
                            <label class="query">
                                <input type="text" name="search" placeholder="{% trans 'Search into website' %}:" value="" data-constraints="@Required" />
                            </label>
                            <button type="submit" class="header-search-btn submit-btn" id="header-search-btn" value="{% trans 'Search' %}">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </header>
    <!-- Header -->
    {% block extra_header %}
	{% placeholder 'Top container' %}
	<span class="line-ct-wrap"><span class="line-ct"></span></span>
    {% endblock extra_header %}
</div>
{% endblock header %}
{% block page_content %}
        <main>
        	<div class="cont">
	        	<div class="post project">
				    {% placeholder 'Content' %}
                    <div class="project-list">
                        {% placeholder 'Lista Extra' %}
                    </div>
					<!-- Social Share -->
                    <ul class="post-share">
                        <li><a data-social="facebook" href="#" title="Share on Facebook" class="js-fbShare"><i class="fa fa-facebook"></i></a></li>
                        <li><a data-social="twitter" href="#" title="Tweet" class="js-twitterShare"><i class="fa fa-twitter"></i></a></li>
                        {% comment %}
                        <li><a data-social="mail" href="#" target="_blank" title="Pin it" class="mailShare"><i class="fa fa-envelope"></i></a></li>
                        {% endcomment %}
                    </ul>
                    <!-- Social Share -->
	        	</div>
	        </div>
        </main>
{% endblock page_content %}

project/templates/cms_templates/home.html
{% extends 'base_site.html' %}
{% load cms_tags %}
{% load menu_tags %}
{% load events_tags %}
{% load portfolio_tags %}
{% load i18n %}
{% load static from staticfiles %}

{% block inline_css %}
	{%  include 'partials/styles.html' %}
{% endblock inline_css %}


{% block body_attrs %}class="homeNs"{% endblock body_attrs %}
{% block header %}
	<div id="" class="top">
		<!-- Header -->
		<header class="header site-header">
			<!-- Logotype -->
			

			<div class="mainmenu-btn" id="mainmenu-btn">
				<div class="navTrigger"><i></i></div>
			</div>
			<!-- Search Form -->
			<div class="header-search searchFormWrapper">
				<a href="#" id="header-search-btn" class="header-search-btn"><i class="fa fa-search"></i></a>
				<form id="header-search" class='' method="post" action="{% url 'base:search-view' %}">
		            {% csrf_token %}
		            <fieldset>
		                <div class="contact-form_block1 btn-wr">
		                    <label class="query">
		                        <input type="text" name="search" placeholder="{% trans 'Search into website' %}:" value="" data-constraints="@Required"/>
		                    </label>
		                    <button type="submit" class="header-search-btn submit-btn" id="header-search-btn" value="{% trans 'Search' %}">
		                    	<i class="fa fa-search"></i>
		                    </button>
		                </div>
		            </fieldset>
		        </form>
			</div>
		</header>
		<!-- Header -->

		{% block extra_header %}
		<div class="siteloader">
			<div class="loader1"></div>
		</div>
		<div class="fullscreen">
			<div class="svgLogoWrapper">
				{% include 'svg/logo_new.svg' %}
			</div>
			<div class="nameWrapper">
				{% include 'svg/scritta.svg' %}
			</div>
		</div>
		{% comment %}
		<div class="fullscreen js-crossfade">
			<div class="logo purple current" data-bgimg="{% static 'img/home_page_1.png' %}">
			</div>
			<div class="logo green" data-bgimg="{% static 'img/home_page_3.png' %}">
			</div>
			<div class="logo yellow" data-bgimg="{% static 'img/home_page_2.png' %}">
			</div>
		</div>
		{% endcomment %}
		{# placeholder "Gallery" #}
		{% endblock extra_header %}

	</div>
{% endblock header %}
{% block page_content %}
    <main>
		<div class="cont front">
			{% comment %}
			<!-- Projects Sections -->
			<div class="cont project-front-sections-wrap" id="project-front-sections">
				<div class="project-front-sections-inner">
					<ul class="project-front-sections">
						<li>
							<a class="active" data-section="*" href="#">All posts</a>
						</li>
						<li>
							<a data-section=".section1" href="#">Stories</a>
						</li>
						<li>
							<a data-section=".section2" href="#">Travels</a>
						</li>
						<li>
							<a data-section=".section3" href="#">Cooking</a>
						</li>
						<li>
							<a data-section=".section4" href="#">Peoples</a>
						</li>
						<li>
							<a data-section=".section5" href="#">Other</a>
						</li>
					</ul>
				</div>
			</div>
			<!-- Projects Sections -->
			{% endcomment %}
			{% comment %}
			<!-- Projects Items -->
			<div class="project-front-list" id="project-front-list">
				<h3 class="tac" style="margin:30px 0;">Prossimi appuntamenti</h3>
				{% last_events_home 3 %}
			</div>
			
			<p class="post-front-link">
				<a href="{% page_url 'uperform' %}" rel="nofollow" target="_blank">Eventi</a>
			</p>
			<!-- Homepage Posts -->

			<!-- Instagram Photos -->
			<ul class="instagram-list js-facebookFeed" id="facebook-list">				
			</ul>
			<p class="instagram-more">
				<a href="https://www.facebook.com/factorhill/" rel="nofollow" target="_blank">Open facebook</a>
			</p>
			<!-- Instagram Photos -->
			{% endcomment %}
		</div>
    </main>
{% endblock page_content %}

{% block fb_app %}
{% static_placeholder 'Facebook App' %}
{% endblock fb_app %}